### ISSUE TITLE
Turnstile Seems To be Broken

### ISSUE THREAD

**Issue by mindhunter77** [bitcart/bitcart-site#139] opened 2024-11-02 16:37 UTC
Filled in both keys and selected turnstile in the settings but after 7 days it seems to be collecting no data. This leads me to think something may not be working. Nothing seen in the log related to turnstile or captcha.

![screenshot](https://github.com/user-attachments/assets/37fdd633-1151-4105-9fe8-d8ef51ab4546)

**Comment by MrNaif2018** [comment] 2024-11-02 16:39
Hi, but isn't turnstile supposed to be captcha, not analytics? Or it's analytics of users trying to solve captcha

**Comment by mindhunter77** [comment] 2024-11-02 16:41
That's just the analytics they show you about your turnstile setup as far as I know. Solve rates, traffic through it, etc as far as I understand. My turnstile setup in cloudflare is named "cart"

**Comment by MrNaif2018** [comment] 2024-11-02 16:43
Are you using latest master? e.g. did you run ./install-master.sh to re-verify? Because it works on the demo

**Comment by mindhunter77** [comment] 2024-11-02 16:44
No, let me try an update and report back.

**Comment by MrNaif2018** [comment] 2024-12-23 01:25
The issue is most likely fixed by now

**Closed as completed by MrNaif2018** 2024-12-23 01:25 UTC
